name: Build workflow

on:
  push:
    branches:
      - feature/*
      - hotfix/*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Get pom version from main
        run: echo "MAIN_POM_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v2

      - name: Get pom version from feature branch
        run: echo "FEATURE_POM_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Check feature version is not behind
        shell: bash
        run: |
          LOWER_VERSION=$(printf '%s\n%s' "${MAIN_POM_VERSION}" "{$FEATURE_POM_VERSION}" | sort -V | head -n 1)
          echo "version from feature: ${FEATURE_POM_VERSION}"
          echo "version from main: ${MAIN_POM_VERSION}"
          echo "lower version: ${LOWER_VERSION}"
          if [ "${FEATURE_POM_VERSION}" == "${LOWER_VERSION}" ]; then
            echo "Pom version in feature branch is behind. Bump version."
            exit 1
          fi

      - run: echo 'building...'
